---
deployment:
  tasks:
    - export DEPLOYPATH=/home/valdiid/public_html/
    - /usr/bin/rsync -r --exclude='.git/' --exclude='.cpanel.yml' . $DEPLOYPATH
    - chmod 755 $DEPLOYPATH
    - chmod 644 $DEPLOYPATH/.htaccess || true
